language: python
python:
    - "3.8"
cache: pip
install:
    - easy_install distribute
    - pip install -r requirements.txt
before_script:
    - python ./src/manage.py runserver &
script:
    - python ./src/manage.py test trips.tests