language: python
python:
    - "3.8"
cache: pip
install:
    - easy_install distribute
    - pip install -r requirements.txt
script:
    - virtualenv newenv
    - source newenv/bin/activate
    - pip install django
    - pip install django-widget-tweaks
    - pip install python-dotenv
    - pip install amadeus
    - ./src/manage.py test trips.tests
    - deactivate