canadian_airports = [
    ('Abbotsford', 'British Columbia (BC)', 'YXX'),
    ('Akulivik', 'Quebec (QC)', 'AKV'),
    ('Alma', 'Quebec (QC)', 'YTF'),
    ('Anahim Lake', 'British Columbia (BC)', 'YAA'),
    ('Angling Lake', 'Ontario (ON)', 'YAX'),
    ('Arctic Bay', 'Nunavut (NU)', 'YAB'),
    ('Arviat', 'Nunavut (NU)', 'YEK'),
    ('Attawapiskat', 'Ontario (ON)', 'YAT'),
    ('Aupaluk', 'Quebec (QC)', 'YPJ'),
    ('Bagotville', 'Quebec (QC)', 'YBG'),
    ('Baie Comeau', 'Quebec (QC)', 'YBC'),
    ('Baker Lake', 'Nunavut (NU)', 'YBK'),
    ('Bathhurst', 'New Brunswick (NB)', 'ZBF'),
    ('Bearskin Lake', 'Ontario (ON)', 'XBE'),
    ('Bella Bella', 'British Columbia (BC)', 'ZEL'),
    ('Bella Coola', 'British Columbia (BC)', 'QBC'),
    ('Berens River', 'Manitoba (MB)', 'YBV'),
    ('Big Trout', 'Ontario (ON)', 'YTL'),
    ('Black Tickle', 'Newfoundland (NL)', 'YBI'),
    ('Blanc Sablon', 'Quebec (QC)', 'YBX'),
    ('Bonaventure', 'Quebec (QC)', 'YVB'),
    ('Brandon', 'Manitoba (MB)', 'YBR'),
    ('Brochet', 'Manitoba (MB)', 'YBT'),
    ('Brockville', 'Ontario (ON)', 'XBR'),
    ('Burns Lake', 'British Columbia (BC)', 'YPZ'),
    ('Calgary', 'AB', 'YYC'),
    ('Cambridge Bay', 'Nunavut (NU)', 'YCB'),
    ('Campbell River', 'British Columbia (BC)', 'YBL'),
    ('Cape Dorset', 'Nunavut (NU)', 'YTE'),
    ('Cartwright', 'Newfoundland (NL)', 'YRF'),
    ('Castlegar', 'British Columbia (BC)', 'YCG'),
    ('Cat Lake', 'Ontario (ON)', 'YAC'),
    ('Chapleau', 'Ontario (ON)', 'YLD'),
    ('Charlottetown', 'Newfoundland (NL)', 'YHG'),
    ('Charlottetown', 'Prince Edward Island (PE)', 'YYG'),
    ('Chatham', 'Ontario (ON)', 'XCM'),
    ('Chesterfield Inlet', 'Nunavut (NU)', 'YCS'),
    ('Chevery', 'Quebec (QC)', 'YHR'),
    ('Chibougamau', 'Quebec (QC)', 'YMT'),
    ('Chisasibi', 'Quebec (QC)', 'YKU'),
    ('Churchill Falls', 'Newfoundland (NL)', 'ZUM'),
    ('Churchill', 'Manitoba (MB)', 'YYQ'),
    ('Clyde River', 'Nunavut (NU)', 'YCY'),
    ('Colville Lake', 'Northwest Territory (NT)', 'YCK'),
    ('Comox', 'British Columbia (BC)', 'YQQ'),
    ('Coral Harbour', 'Nunavut (NU)', 'YZS'),
    ('Cornwall', 'Ontario (ON)', 'YCC'),
    ('Courtenay', 'British Columbia (BC)', 'YCA'),
    ('Cranbrook', 'British Columbia (BC)', 'YXC'),
    ('Cross Lake', 'Manitoba (MB)', 'YCR'),
    ('Dauphin', 'Manitoba (MB)', 'YDN'),
    ('Davis Inlet', 'Newfoundland (NL)', 'YDI'),
    ('Dawson City', 'Yukon Territory (YT)', 'YDA'),
    ('Dawson Creek', 'British Columbia (BC)', 'YDQ'),
    ('Deer Lake', 'Newfoundland (NL)', 'YDF'),
    ('Deer Lake', 'Ontario (ON)', 'YVZ'),
    ('Deline', 'Northwest Territory (NT)', 'YWJ'),
    ('Dryden', 'Ontario (ON)', 'YHD'),
    ('Duncan/Quam', 'British Columbia (BC)', 'DUQ'),
    ('East Main', 'Quebec (QC)', 'ZEM'),
    ('Edmonton', 'AB - International', 'YEG'),
    ('Esquimalt', 'British Columbia (BC)', 'YPF'),
    ('Flin Flon', 'Manitoba (MB)', 'YFO'),
    ('Fond du Lac', 'Saskatchewan (SK)', 'ZFD'),
    ('Fort Albany', 'Ontario (ON)', 'YFA'),
    ('Fort Chipewyan', 'AB', 'YPY'),
    ('Fort Frances', 'Ontario (ON)', 'YAG'),
    ('Fort Good Hope', 'Northwest Territory (NT)', 'YGH'),
    ('Fort Hope', 'Ontario (ON)', 'YFH'),
    ('Fort Mcmurray', 'AB', 'YMM'),
    ('Fort Nelson', 'British Columbia (BC)', 'YYE'),
    ('Fort Severn', 'Ontario (ON)', 'YER'),
    ('Fort Simpson', 'Northwest Territory (NT)', 'YFS'),
    ('Fort Smith', 'Northwest Territory (NT)', 'YSM'),
    ('Fort St John', 'British Columbia (BC)', 'YXJ'),
    ('Fox Harbour/St Lewis', 'Newfoundland (NL)', 'YFX'),
    ('Fredericton', 'New Brunswick (NB)', 'YFC'),
    ('Gander', 'Newfoundland (NL)', 'YQX'),
    ('Gaspe', 'Quebec (QC)', 'YGP'),
    ('Gethsemani', 'Quebec (QC)', 'ZGS'),
    ('Gillam', 'Manitoba (MB)', 'YGX'),
    ('Gillies Bay', 'British Columbia (BC)', 'YGB'),
    ('Gjoa Haven', 'Nunavut (NU)', 'YHK'),
    ('Gods Narrows', 'Manitoba (MB)', 'YGO'),
    ('Gods River', 'Manitoba (MB)', 'ZGI'),
    ('Goose Bay', 'Newfoundland (NL)', 'YYR'),
    ('Grande Prairie', 'AB', 'YQU'),
    ('Grimsby', 'Ontario (ON)', 'XGY'),
    ('Grise Fiord', 'Nunavut (NU)', 'YGZ'),
    ('Halifax', 'Nova Scotia (NS) - International', 'YHZ'),
    ('Hall Beach', 'Nunavut (NU)', 'YUX'),
    ('Hamilton', 'Ontario (ON)', 'YHM'),
    ('Havre St Pierre', 'Quebec (QC)', 'YGV'),
    ('Hay River', 'Northwest Territory (NT)', 'YHY'),
    ('High Level', 'AB', 'YOJ'),
    ('Holman', 'Northwest Territory (NT)', 'YHI'),
    ('Hopedale', 'Newfoundland (NL)', 'YHO'),
    ('Houston', 'British Columbia (BC) - Bus station', 'ZHO'),
    ('Hudson Bay', 'Saskatchewan (SK)', 'YHB'),
    ('Igloolik', 'Nunavut (NU)', 'YGT'),
    ('Iles De La Madeleine', 'Quebec (QC)', 'YGR'),
    ('Ilford', 'Manitoba (MB)', 'ILF'),
    ('Inukjuak', 'Quebec (QC)', 'YPH'),
    ('Inuvik', 'Northwest Territory (NT)', 'YEV'),
    ('Iqaluit', 'Nunavut (NU)', 'YFB'),
    ('Island Lake/Garden Hill', 'Manitoba (MB)', 'YIV'),
    ('Ivujivik', 'Quebec (QC)', 'YIK'),
    ('Kamloops', 'British Columbia (BC)', 'YKA'),
    ('Kangiqsualujjuaq', 'Quebec (QC)', 'XGR'),
    ('Kangiqsujuaq', 'Quebec (QC)', 'YWB'),
    ('Kangirsuk', 'Quebec (QC)', 'YKG'),
    ('Kapuskasing', 'Ontario (ON)', 'YYU'),
    ('Kasabonika', 'Ontario (ON)', 'XKS'),
    ('Kaschechewan', 'Ontario (ON)', 'ZKE'),
    ('Keewaywin', 'Ontario (ON)', 'KEW'),
    ('Kegaska', 'Quebec (QC)', 'ZKG'),
    ('Kelowna', 'British Columbia (BC)', 'YLW'),
    ('Kenora', 'Ontario (ON)', 'YQK'),
    ('Kimmirut/Lake Harbour ', 'Nunavut (NU)', 'YLC'),
    ('Kingfisher Lake', 'Ontario (ON)', 'KIF'),
    ('Kingston', 'Ontario (ON) - Norman Rogers Airport', 'YGK'),
    ('Kitchener', 'Ontario (ON)', 'YKF'),
    ('Klemtu', 'British Columbia (BC)', 'YKT'),
    ('Kugaaruk', 'Nunavut (NU)', 'YBB'),
    ('Kugluktuk/Coppermine', 'Nunavut (NU)', 'YCO'),
    ('Kuujjuaq', 'Quebec (QC)', 'YVP'),
    ('Kuujjuarapik', 'Quebec (QC)', 'YGW'),
    ('La Grande', 'Quebec (QC)', 'YGL'),
    ('La Ronge', 'Saskatchewan (SK)', 'YVC'),
    ('La Tabatiere', 'Quebec (QC)', 'ZLT'),
    ('La Tuque', 'Quebec (QC)', 'YLQ'),
    ('Lac Brochet', 'Manitoba (MB)', 'XLB'),
    ('Lansdowne House', 'Ontario (ON)', 'YLH'),
    ('Leaf Rapids', 'Manitoba (MB)', 'YLR'),
    ('Lethbridge', 'AB', 'YQL'),
    ('Lloydminister', 'AB', 'YLL'),
    ('London', 'Ontario (ON) - Municipal Airport', 'YXU'),
    ('Lutselke/Snowdrift', 'Northwest Territory (NT)', 'YSG'),
    ("Mary's Harbour", 'Newfoundland (NL)', 'YMH'),
    ('Medicine Hat', 'AB', 'YXH'),
    ('Moncton', 'New Brunswick (NB) - Airport', 'YQM'),
    ('Mont Joli', 'Quebec (QC)', 'YYY'),
    ('Montreal', 'Quebec (QC) - all airports', 'YMQ'),
    ('Montreal', 'Quebec (QC) - Dorval', 'YUL'),
    ('Montreal', 'Quebec (QC) - Mirabel', 'YMX'),
    ('Moosonee', 'Ontario (ON)', 'YMO'),
    ('Muskrat Dam', 'Ontario (ON)', 'MSA'),
    ('Nain', 'Newfoundland (NL)', 'YDP'),
    ('Nakina', 'Ontario (ON)', 'YQN'),
    ('Nanaimo', 'British Columbia (BC) - Harbour Airport', 'ZNA'),
    ('Nanaimo', 'British Columbia (BC) - Cassidy Airport', 'YCD'),
    ('Nanisivik', 'Nunavut (NU)', 'YSR'),
    ('Natashquan', 'Quebec (QC)', 'YNA'),
    ('Nemiscau', 'Quebec (QC)', 'YNS'),
    ('Noranda/Rouyn', 'Quebec (QC)', 'YUY'),
    ('Norman Wells', 'Northwest Territory (NT)', 'YVQ'),
    ('North Bay', 'Ontario (ON)', 'YYB'),
    ('North Spirit Lake', 'Ontario (ON)', 'YNO'),
    ('Norway House', 'Manitoba (MB)', 'YNE'),
    ('Ogoki', 'Ontario (ON)', 'YOG'),
    ('Old Crow', 'Yukon Territory (YT)', 'YOC'),
    ('Opapamiska Lake', 'Ontario (ON)', 'YBS'),
    ('Oshawa', 'Ontario (ON)', 'YOO'),
    ('Ottawa', 'Ontario (ON) - International', 'YOW'),
    ('Oxford House', 'Manitoba (MB)', 'YOH'),
    ('Pakuashipi', 'Quebec (QC)', 'YIF'),
    ('Pangnirtung', 'Nunavut (NU)', 'YXP'),
    ('Paulatuk', 'Northwest Territory (NT)', 'YPC'),
    ('Peace River', 'AB', 'YPE'),
    ('Peawanuck', 'Ontario (ON)', 'YPO'),
    ('Pembroke', 'Ontario (ON)', 'YTA'),
    ('Penticton', 'British Columbia (BC)', 'YYF'),
    ('Pickle Lake', 'Ontario (ON)', 'YPL'),
    ('Pikangikum', 'Ontario (ON)', 'YPM'),
    ('Points North Landing', 'Saskatchewan (SK)', 'YNL'),
    ('Pond Inlet', 'Nunavut (NU)', 'YIO'),
    ('Poplar Hill', 'Ontario (ON)', 'YHP'),
    ('Port Alberni', 'British Columbia (BC)', 'YPB'),
    ('Port Hardy', 'British Columbia (BC)', 'YZT'),
    ('Port Hope Simpson', 'Newfoundland (NL)', 'YHA'),
    ('Port Meiner', 'Quebec (QC)', 'YPN'),
    ('Postville', 'Newfoundland (NL)', 'YSO'),
    ('Povungnituk', 'Quebec (QC)', 'YPX'),
    ('Powell River', 'British Columbia (BC)', 'YPW'),
    ('Prince Albert', 'Saskatchewan (SK)', 'YPA'),
    ('Prince George', 'British Columbia (BC)', 'YXS'),
    ('Prince Rupert', 'British Columbia (BC) - Digby Island Airport', 'YPR'),
    ('Pukatawagan', 'Manitoba (MB) -', 'XPK'),
    ('Qikiqtarjuaq', 'Nunavut (NU)', 'YVM'),
    ('Qualicum', 'British Columbia (BC)', 'XQU'),
    ('Quaqtaq', 'Quebec (QC)', 'YQC'),
    ('Quebec', 'Quebec (QC) - International Airport', 'YQB'),
    ('Quesnel', 'British Columbia (BC)', 'YQZ'),
    ('Rae Lakes', 'Northwest Territory (NT)', 'YRA'),
    ('Rainbow Lake', 'AB', 'YOP'),
    ('Rankin Inlet', 'Nunavut (NU)', 'YRT'),
    ('Red Lake', 'Ontario (ON)', 'YRL'),
    ('Red Sucker Lake', 'Manitoba (MB)', 'YRS'),
    ('Regina', 'Saskatchewan (SK)', 'YQR'),
    ('Repulse Bay', 'Nunavut (NU)', 'YUT'),
    ('Resolute', 'Nunavut (NU)', 'YRB'),
    ('Rigolet', 'Newfoundland (NL)', 'YRG'),
    ('Rimouski', 'Quebec (QC)', 'YXK'),
    ('Roberval', 'Quebec (QC)', 'YRJ'),
    ('Round Lake', 'Ontario (ON)', 'ZRJ'),
    ('Rouyn/Noranda', 'Quebec (QC)', 'YUY'),
    ('Sachigo Lake', 'Ontario (ON)', 'ZPB'),
    ('Sachs Harbour', 'Northwest Territory (NT)', 'YSY'),
    ('Saint John', 'New Brunswick (NB)', 'YSJ'),
    ('Saint Johns', 'Newfoundland (NL)', 'YYT'),
    ('Saint Leonard', 'New Brunswick (NB)', 'YSL'),
    ('Salluit', 'Quebec (QC)', 'YZG'),
    ('Sandy Lake', 'Ontario (ON)', 'ZSJ'),
    ('Sanikiluaq', 'Nunavut (NU)', 'YSK'),
    ('Sarnia', 'Ontario (ON)', 'YZR'),
    ('Saskatoon', 'Saskatchewan (SK)', 'YXE'),
    ('Sault Ste-Marie', 'Ontario (ON)', 'YAM'),
    ('Schefferville', 'Quebec (QC)', 'YKL'),
    ('Sept-Iles', 'Quebec (QC)', 'YZV'),
    ('Shamattawa', 'Manitoba (MB)', 'ZTM'),
    ('Sioux Lookout', 'Ontario (ON)', 'YXL'),
    ('Smith Falls', 'Ontario (ON)', 'YSH'),
    ('Smithers', 'British Columbia (BC)', 'YYD'),
    ('Snare Lake', 'Northwest Territory (NT)', 'YFJ'),
    ('South Indian Lake', 'Manitoba (MB)', 'XSI'),
    ('St Anthony', 'Newfoundland (NL)', 'YAY'),
    ('St Catharines', 'Ontario (ON)', 'YCM'),
    ('Ste Therese Point', 'Manitoba (MB)', 'YST'),
    ('Stephenville', 'Newfoundland (NL)', 'YJT'),
    ('Stony Rapids', 'Saskatchewan (SK)', 'YSF'),
    ('Sudbury', 'Ontario (ON)', 'YSB'),
    ('Summer Beaver', 'Ontario (ON)', 'SUR'),
    ('Swan River', 'Manitoba (MB)', 'ZJN'),
    ('Sydney', 'Nova Scotia (NS)', 'YQY'),
    ('Tadoule Lake', 'Manitoba (MB)', 'XTL'),
    ('Taloyoak', 'Nunavut (NU)', 'YYH'),
    ('Tasiujuaq', 'Quebec (QC)', 'YTQ'),
    ('Terrace', 'British Columbia (BC)', 'YXT'),
    ('Tete-a-La Baleine', 'Quebec (QC)', 'ZTB'),
    ('The Pas', 'Manitoba (MB)', 'YQD'),
    ('Thicket Portage', 'Manitoba (MB)', 'YTD'),
    ('Thompson', 'Manitoba (MB)', 'YTH'),
    ('Thunder Bay', 'Ontario (ON)', 'YQT'),
    ('Timmins', 'Ontario (ON)', 'YTS'),
    ('Tofino', 'British Columbia (BC)', 'YAZ'),
    ('Toronto', 'Ontario (ON) - Toronto Island Airport', 'YTZ'),
    ('Toronto', 'Ontario (ON) - International', 'YYZ'),
    ('Tuktoyaktuk', 'Northwest Territory (NT)', 'YUB'),
    ('Tulita/Fort Norman', 'Northwest Territory (NT)', 'ZFN'),
    ('Umiujag', 'Quebec (QC)', 'YUD'),
    ('Uranium City', 'Saskatchewan (SK)', 'YBE'),
    ("Val-d'Or", 'Quebec (QC)', 'YVO'),
    ('Vancouver', 'British Columbia (BC) - Coal Harbour', 'CXH'),
    ('Vancouver', 'British Columbia (BC) - International', 'YVR'),
    ('Victoria', 'British Columbia (BC) - Inner Harbor', 'YWH'),
    ('Victoria', 'British Columbia (BC) - International', 'YYJ'),
    ('Wabush', 'Newfoundland (NL)', 'YWK'),
    ('Waskaganish', 'Quebec (QC)', 'YKQ'),
    ('Webequie', 'Ontario (ON)', 'YWP'),
    ('Wemindji', 'Quebec (QC)', 'YNC'),
    ('Wha Ti/Lac La Martre', 'Northwest Territory (NT)', 'YLE'),
    ('Whale Cove', 'Nunavut (NU)', 'YXN'),
    ('White River', 'Ontario (ON)', 'YWR'),
    ('Whitehorse', 'Yukon Territory (YT)', 'YXY'),
    ('Williams Harbour', 'Newfoundland (NL)', 'YWM'),
    ('Williams Lake', 'British Columbia (BC)', 'YWL'),
    ('Windsor', 'Ontario (ON)', 'YQG'),
    ('Winnipeg', 'Manitoba (MB) - International', 'YWG'),
    ('Wollaston Lake', 'Saskatchewan (SK)', 'ZWL'),
    ('Wunnummin Lake', 'Ontario (ON)', 'WNN'),
    ('Yarmouth', 'Nova Scotia (NS)', 'YQI'),
    ('Yellowknife', 'Northwest Territory (NT)', 'YZF'),
    ('York Landing', 'Manitoba (MB)', 'ZAC')
]
