world_regions = {
    "Africa":[],
    "Asia":[],
    "Central America":[],
    "Europe":[],
    "Middle East":[],
    "North America":[],
    "Oceania":[],
    "South America":[],
    "The Caribbean":[]
}
world_regions['Africa'].append("Burundi")
world_regions['Africa'].append("Comoros")
world_regions['Africa'].append("Djibouti")
world_regions['Africa'].append("Eritrea")
world_regions['Africa'].append("Ethiopia")
world_regions['Africa'].append("Kenya")
world_regions['Africa'].append("Madagascar")
world_regions['Africa'].append("Malawi")
world_regions['Africa'].append("Mauritius")
world_regions['Africa'].append("Mayotte")
world_regions['Africa'].append("Mozambique")
world_regions['Africa'].append("Reunion")
world_regions['Africa'].append("Rwanda")
world_regions['Africa'].append("Seychelles")
world_regions['Africa'].append("Somalia")
world_regions['Africa'].append("Tanzania")
world_regions['Africa'].append("Uganda")
world_regions['Africa'].append("Zambia")
world_regions['Africa'].append("Zimbabwe")
world_regions['Africa'].append("Angola")
world_regions['Africa'].append("Cameroon")
world_regions['Africa'].append("Central African Republic")
world_regions['Africa'].append("Chad")
world_regions['Africa'].append("Congo")
world_regions['Africa'].append("Equatorial Guinea")
world_regions['Africa'].append("Gabon")
world_regions['Africa'].append("Sao Tome and Principe")
world_regions['Africa'].append("Algeria")
world_regions['Africa'].append("Egypt")
world_regions['Africa'].append("Libya")
world_regions['Africa'].append("Morocco")
world_regions['Africa'].append("South Sudan")
world_regions['Africa'].append("Sudan")
world_regions['Africa'].append("Tunisia")
world_regions['Africa'].append("Western Sahara")
world_regions['Africa'].append("Botswana")
world_regions['Africa'].append("Eswatini (ex-Swaziland)")
world_regions['Africa'].append("Lesotho")
world_regions['Africa'].append("Namibia")
world_regions['Africa'].append("South Africa")
world_regions['Africa'].append("Benin")
world_regions['Africa'].append("Burkina Faso")
world_regions['Africa'].append("Cape Verde")
world_regions['Africa'].append("Cote d'Ivoire (Ivory Coast)")
world_regions['Africa'].append("Gambia")
world_regions['Africa'].append("Ghana")
world_regions['Africa'].append("Guinea")
world_regions['Africa'].append("Guinea-Bissau")
world_regions['Africa'].append("Liberia")
world_regions['Africa'].append("Mali")
world_regions['Africa'].append("Mauritania")
world_regions['Africa'].append("Niger")
world_regions['Africa'].append("Nigeria")
world_regions['Africa'].append("Saint Helena")
world_regions['Africa'].append("Senegal")
world_regions['Africa'].append("Sierra Leone")
world_regions['Africa'].append("Togo")
world_regions['Africa'].sort()

world_regions['The Caribbean'].append("Anguilla")
world_regions['The Caribbean'].append("Antigua and Barbuda")
world_regions['The Caribbean'].append("Aruba")
world_regions['The Caribbean'].append("Bahamas")
world_regions['The Caribbean'].append("Barbados")
world_regions['The Caribbean'].append("Bonaire, Saint Eustatius and Saba")
world_regions['The Caribbean'].append("British Virgin Islands")
world_regions['The Caribbean'].append("Cayman Islands")
world_regions['The Caribbean'].append("Cuba")
world_regions['The Caribbean'].append("Curaçao")
world_regions['The Caribbean'].append("Dominica")
world_regions['The Caribbean'].append("Dominican Republic")
world_regions['The Caribbean'].append("Grenada")
world_regions['The Caribbean'].append("Guadeloupe")
world_regions['The Caribbean'].append("Haiti")
world_regions['The Caribbean'].append("Jamaica")
world_regions['The Caribbean'].append("Martinique")
world_regions['The Caribbean'].append("Monserrat")
world_regions['The Caribbean'].append("Netherlands Antilles")
world_regions['The Caribbean'].append("Puerto Rico")
world_regions['The Caribbean'].append("Saint-Barthélemy")
world_regions['The Caribbean'].append("St. Kitts and Nevis")
world_regions['The Caribbean'].append("Saint Lucia")
world_regions['The Caribbean'].append("Saint Martin")
world_regions['The Caribbean'].append("Saint Vincent and the Grenadines")
world_regions['The Caribbean'].append("Sint Maarten")
world_regions['The Caribbean'].append("Trinidad and Tobago")
world_regions['The Caribbean'].append("Turks and Caicos Islands")
world_regions['The Caribbean'].append("U.S. Virgin Islands")
world_regions['The Caribbean'].sort()

world_regions['Central America'].append("Belize")
world_regions['Central America'].append("Costa Rica")
world_regions['Central America'].append("El Salvador")
world_regions['Central America'].append("Guatemala")
world_regions['Central America'].append("Honduras")
world_regions['Central America'].append("Mexico")
world_regions['Central America'].append("Nicaragua")
world_regions['Central America'].append("Panama")
world_regions['Central America'].sort()

world_regions['South America'].append("Argentina")
world_regions['South America'].append("Bolivia")
world_regions['South America'].append("Brazil")
world_regions['South America'].append("Chile")
world_regions['South America'].append("Colombia")
world_regions['South America'].append("Ecuador")
world_regions['South America'].append("Falkland Islands")
world_regions['South America'].append("French Guiana")
world_regions['South America'].append("Guyana")
world_regions['South America'].append("Paraguay")
world_regions['South America'].append("Peru")
world_regions['South America'].append("Suriname")
world_regions['South America'].append("Uruguay")
world_regions['South America'].append("Venezuela")
world_regions['South America'].sort()

world_regions['North America'].append("Canada")
world_regions['North America'].append("United States")
world_regions['North America'].sort()

world_regions['Asia'].append("Afganistan")
world_regions['Asia'].append("Armenia")
world_regions['Asia'].append("Azerbaijan")
world_regions['Asia'].append("Bangladesh")
world_regions['Asia'].append("Bhutan")
world_regions['Asia'].append("Brunei Darussalam")
world_regions['Asia'].append("Cambodia")
world_regions['Asia'].append("China")
world_regions['Asia'].append("Georgia")
world_regions['Asia'].append("Hong Kong")
world_regions['Asia'].append("India")
world_regions['Asia'].append("Indonesia")
world_regions['Asia'].append("Japan")
world_regions['Asia'].append("Kazakhstan")
world_regions['Asia'].append("North Korea")
world_regions['Asia'].append("South Korea")
world_regions['Asia'].append("Kyrgyzstan")
world_regions['Asia'].append("Laos")
world_regions['Asia'].append("Macao")
world_regions['Asia'].append("Malaysia")
world_regions['Asia'].append("Maldives")
world_regions['Asia'].append("Mongolia")
world_regions['Asia'].append("Myanmar")
world_regions['Asia'].append("Nepal")
world_regions['Asia'].append("Pakistan")
world_regions['Asia'].append("Philippines")
world_regions['Asia'].append("Singapore")
world_regions['Asia'].append("Sri Lanka")
world_regions['Asia'].append("Taiwan")
world_regions['Asia'].append("Tajikistan")
world_regions['Asia'].append("Thailand")
world_regions['Asia'].append("Timor Leste (West)")
world_regions['Asia'].append("Turkmenistan")
world_regions['Asia'].append("Uzbekistan")
world_regions['Asia'].append("Vietnam")
world_regions['Asia'].append("Viet Nam")
world_regions['Asia'].sort()



world_regions['Europe'].append("France")
world_regions['Europe'].append("Germany")
world_regions['Europe'].append("Italy")
world_regions['Europe'].append("Portugal")
world_regions['Europe'].append("Spain")
world_regions['Europe'].append("United Kingdom")
world_regions['Europe'].sort()

world_regions['Middle East'].append("Israel")
world_regions['Middle East'].append("Jordan")
world_regions['Middle East'].append("Saudi Arabia")
world_regions['Middle East'].append("United Arab Emirates")
world_regions['Middle East'].sort()

world_regions['Oceania'].append("Australia")
world_regions['Oceania'].append("New Zealand")
world_regions['Oceania'].sort()