us_airports = [
    ('Aberdeen', 'South Dakota (SD)', 'ABR'),
    ('Abilene', 'Texas (TX)', 'ABI'),
    ('Adak Island', 'Alaska (AK)', 'ADK'),
    ('Akiachak', 'Alaska (AK)', 'KKI'),
    ('Akiak', 'Alaska (AK)', 'AKI'),
    ('Akron/Canton', 'Ohio (OH)', 'CAK'),
    ('Akuton', 'Alaska (AK)', 'KQA'),
    ('Alakanuk', 'Alaska (AK)', 'AUK'),
    ('Alamogordo', 'New Mexico (NM)', 'ALM'),
    ('Alamosa', 'Colorado (CO)', 'ALS'),
    ('Albany', 'New York (NY)', 'ALB'),
    ('Albuquerque', 'New Mexico (NM)', 'ABQ'),
    ('Aleknagik', 'Alaska (AK)', 'WKK'),
    ('Alexandria', 'Louisiana (LA)', 'AEX'),
    ('Allakaket', 'Alaska (AK)', 'AET'),
    ('Allentown', 'Pennsylvania (PA)', 'ABE'),
    ('Alliance', 'Nebraska (NE)', 'AIA'),
    ('Alpena', 'Michigan (MI)', 'APN'),
    ('Altoona', 'Pennsylvania (PA)', 'AOO'),
    ('Amarillo', 'Texas (TX)', 'AMA'),
    ('Ambler', 'Alaska (AK)', 'ABL'),
    ('Anaktueuk', 'Alaska (AK)', 'AKP'),
    ('Anchorage', 'Alaska (AK)', 'ANC'),
    ('Angoon', 'Alaska (AK)', 'AGN'),
    ('Aniak', 'Alaska (AK)', 'ANI'),
    ('Anvik', 'Alaska (AK)', 'ANV'),
    ('Appleton', 'Wisconsin (WI)', 'ATW'),
    ('Arcata', 'California (CA)', 'ACV'),
    ('Arctic Village', 'Alaska (AK)', 'ARC'),
    ('Asheville', 'North Carolina (NC)', 'AVL'),
    ('Ashland', 'Kentucky (KY)/Huntington, WV', 'HTS'),
    ('Aspen', 'Colorado (CO)', 'ASE'),
    ('Athens', 'Georgia (GA)', 'AHN'),
    ('Atka', 'Alaska (AK)', 'AKB'),
    ('Atlanta', 'Georgia (GA)', 'ATL'),
    ('Atlantic City', 'New Jersey (NJ)', 'AIY'),
    ('Atqasuk', 'Alaska (AK)', 'ATK'),
    ('Augusta', 'Georgia (GA)', 'AGS'),
    ('Augusta', 'Maine (ME)', 'AUG'),
    ('Austin', 'Texas (TX)', 'AUS'),
    ('Bakersfield', 'California (CA)', 'BFL'),
    ('Baltimore', 'Maryland (MD)', 'BWI'),
    ('Bangor', 'Maine (ME)', 'BGR'),
    ('Bar Harbour', 'Maine (ME)', 'BHB'),
    ('Barrow', 'Alaska (AK)', 'BRW'),
    ('Barter Island', 'Alaska (AK)', 'BTI'),
    ('Baton Rouge', 'Louisiana (LA)', 'BTR'),
    ('Bay City', 'Michigan (MI)', 'MBS'),
    ('Beaumont/Port Arthur', 'Texas (TX)', 'BPT'),
    ('Beaver Creek', 'Colorado (CO) - Van service', 'ZBV'),
    ('Beaver', 'Alaska (AK)', 'WBQ'),
    ('Beckley', 'West Virginia (WV)', 'BKW'),
    ('Bedford', 'Massachusetts (MA)', 'BED'),
    ('Belleville', 'Illinois (IL)', 'BLV'),
    ('Bellingham', 'Washington (WA)', 'BLI'),
    ('Bemidji', 'Minnesota (MN)', 'BJI'),
    ('Benton Harbor', 'Michigan (MI)', 'BEH'),
    ('Bethel', 'Alaska (AK)', 'BET'),
    ('Bethlehem', 'Pennsylvania (PA)', 'ABE'),
    ('Bettles', 'Alaska (AK)', 'BTT'),
    ('Billings', 'Montana (MT)', 'BIL'),
    ('Biloxi/Gulfport', 'Mississippi (MS)', 'GPT'),
    ('Binghamton', 'New York (NY)', 'BGM'),
    ('Birch Creek', 'Alaska (AK)', 'KBC'),
    ('Birmingham', 'Alabama (AL)', 'BHM'),
    ('Bismarck', 'North Dakota (ND)', 'BIS'),
    ('Block Island', 'Rhode Island (RI)', 'BID'),
    ('Bloomington', 'Illinois (IL)', 'BMI'),
    ('Bluefield', 'West Virginia (WV)', 'BLF'),
    ('Boise', 'Idaho (ID)', 'BOI'),
    ('Boston', 'Massachusetts (MA)', 'BOS'),
    ('Boulder', 'Colorado (CO) - Municipal Airport', 'WBU'),
    ('Boundary', 'Alaska (AK)', 'BYA'),
    ('Bowling Green', 'Kentucky (KY)', 'BWG'),
    ('Bozeman', 'Montana (MT)', 'BZN'),
    ('Bradford', 'Pennsylvania (PA)', 'BFD'),
    ('Brainerd', 'Minnesota (MN)', 'BRD'),
    ('Brawnwood', 'Texas (TX)', 'BWD'),
    ('Breckonridge', 'Colorado (CO) - Van service', 'QKB'),
    ('Bristol', 'Virginia (VA)', 'TRI'),
    ('Brookings', 'South Dakota (SD)', 'BKX'),
    ('Brooks Lodge', 'Alaska (AK)', 'RBH'),
    ('Brownsville', 'Texas (TX)', 'BRO'),
    ('Brunswick', 'Georgia (GA)', 'BQK'),
    ('Buckland', 'Alaska (AK)', 'BKC'),
    ('Buffalo', 'New York (NY)', 'BUF'),
    ('Bullhead City/Laughlin', 'Arizona (AZ)', 'IFP'),
    ('Burbank', 'California (CA)', 'BUR'),
    ('Burlington', 'Iowa (IA)', 'BRL'),
    ('Burlington', 'Vermont (VT)', 'BTV'),
    ('Butte', 'Montana (MT)', 'BTM'),
    ('Canton/Akron', 'Ohio (OH)', 'CAK'),
    ('Cape Girardeau', 'Missouri (MO)', 'CGI'),
    ('Cape Lisburne', 'Alaska (AK)', 'LUR'),
    ('Cape Newenham', 'Alaska (AK)', 'EHM'),
    ('Carbondale', 'Illinois (IL)', 'MDH'),
    ('Carlsbad', 'California (CA)', 'CLD'),
    ('Carlsbad', 'New Mexico (NM)', 'CNM'),
    ('Carmel', 'California (CA)', 'MRY'),
    ('Casper', 'Wyoming (WY)', 'CPR'),
    ('Cedar City', 'Utah (UT)', 'CDC'),
    ('Cedar Rapids', 'Iowa (IA)', 'CID'),
    ('Central', 'Alaska (AK)', 'CEM'),
    ('Chadron', 'Nebraska (NE)', 'CDR'),
    ('Chalkyitsik', 'Alaska (AK)', 'CIK'),
    ('Champaign/Urbana', 'Illinois (IL)', 'CMI'),
    ('Charleston', 'South Carolina (SC)', 'CHS'),
    ('Charleston', 'West Virginia (WV)', 'CRW'),
    ('Charlotte', 'North Carolina (NC)', 'CLT'),
    ('Charlottesville', 'Virginia (VA)', 'CHO'),
    ('Chattanooga', 'Tennessee (TN)', 'CHA'),
    ('Chefornak', 'Alaska (AK)', 'CYF'),
    ('Chevak', 'Alaska (AK)', 'VAK'),
    ('Cheyenne', 'Wyoming (WY)', 'CYS'),
    ('Chicago', 'Illinois (IL) - Meigs', 'CGX'),
    ('Chicago', 'Illinois (IL) - All airports', 'CHI'),
    ('Chicago', 'Illinois (IL) - Midway', 'MDW'),
    ('Chicago', "Illinois (IL) - O'Hare", 'ORD'),
    ('Chicken', 'Alaska (AK)', 'CKX'),
    ('Chico', 'California (CA)', 'CIC'),
    ('Chignik', 'Alaska (AK) - Fisheries', 'KCG'),
    ('Chignik', 'Alaska (AK) -', 'KCQ'),
    ('Chignik', 'Alaska (AK) - Lagoon', 'KCL'),
    ('Chisana', 'Alaska (AK)', 'CZN'),
    ('Chisholm/Hibbing', 'Minnesota (MN)', 'HIB'),
    ('Chuathbaluk', 'Alaska (AK)', 'CHU'),
    ('Cincinnati', 'Ohio (OH)', 'CVG'),
    ('Circle Hot Springs', 'Alaska (AK)', 'CHP'),
    ('Circle', 'Alaska (AK)', 'IRC'),
    ('Clarks Point', 'Alaska (AK)', 'CLP'),
    ('Clarksburg', 'West Virginia (WV)', 'CKB'),
    ('Clearwater/St Petersburg', 'Florida (FL)', 'PIE'),
    ('Cleveland', 'Ohio (OH)', 'CLE'),
    ('Clovis', 'New Mexico (NM)', 'CVN'),
    ('Cody/Yellowstone', 'Wyoming (WY)', 'COD'),
    ('Coffee Point', 'Alaska (AK)', 'CFA'),
    ('Coffman Cove', 'Alaska (AK)', 'KCC'),
    ('Cold Bay', 'Alaska (AK)', 'CDB'),
    ('College Station', 'Texas (TX)', 'CLL'),
    ('Colorado Springs', 'Colorado (CO)', 'COS'),
    ('Columbia', 'Missouri (MO)', 'COU'),
    ('Columbia', 'South Carolina (SC)', 'CAE'),
    ('Columbus', 'Georgia (GA)', 'CSG'),
    ('Columbus', 'Mississippi (MS)', 'GTR'),
    ('Columbus', 'Ohio (OH)', 'CMH'),
    ('Concord', 'California (CA)', 'CCR'),
    ('Concordia', 'Kansas (KS)', 'CNK'),
    ('Copper Mountain', 'Colorado (CO) - Van service', 'QCE'),
    ('Cordova', 'Alaska (AK)', 'CDV'),
    ('Corpus Christi', 'Texas (TX)', 'CRP'),
    ('Cortez', 'Colorado (CO)', 'CEZ'),
    ('Craig', 'Alaska (AK)', 'CGA'),
    ('Crescent City', 'California (CA)', 'CEC'),
    ('Crooked Creek', 'Alaska (AK)', 'CKO'),
    ('Cube Cove', 'Alaska (AK)', 'CUW'),
    ('Cumberland', 'Maryland (MD)', 'CBE'),
    ('Dallas/Fort Worth', 'Texas (TX)', 'DFW'),
    ('Dayton', 'Ohio (OH)', 'DAY'),
    ('Daytona Beach', 'Florida (FL)', 'DAB'),
    ('Decatur', 'Illinois (IL)', 'DEC'),
    ('Deering', 'Alaska (AK)', 'DRG'),
    ('Delta Junction', 'Alaska (AK)', 'DJN'),
    ('Denver', 'Colorado (CO) - International', 'DEN'),
    ('Des Moines', 'Iowa (IA)', 'DSM'),
    ('Detroit', 'Michigan (MI) - All airports', 'DTT'),
    ('Detroit', 'Michigan (MI) - Metro/Wayne County', 'DTW'),
    ("Devil's Lake", 'North Dakota (ND)', 'DVL'),
    ('Dickinson', 'North Dakota (ND)', 'DIK'),
    ('Dillingham', 'Alaska (AK)', 'DLG'),
    ('Dodge City', 'Kansas (KS)', 'DDC'),
    ('Dothan', 'Alabama (AL)', 'DHN'),
    ('Dubois', 'Pennsylvania (PA)', 'DUJ'),
    ('Dubuque', 'Iowa (IA)', 'DBQ'),
    ('Duluth', 'Minnesota (MN)', 'DLH'),
    ('Durango', 'Colorado (CO)', 'DRO'),
    ('Durham', 'North Carolina (NC)', 'RDU'),
    ('Durham/Raleigh', 'North Carolina (NC)', 'RDU'),
    ('Dutch Harbor', 'Alaska (AK)', 'DUT'),
    ('Easton', 'Pennsylvania (PA)', 'ABE'),
    ('Eau Claire', 'Wisconsin (WI)', 'EAU'),
    ('Edna Bay', 'Alaska (AK)', 'EDA'),
    ('Eek', 'Alaska (AK)', 'EEK'),
    ('Ekuk', 'Alaska (AK)', 'KKU'),
    ('Ekwok', 'Alaska (AK)', 'KEK'),
    ('El Centro', 'California (CA)', 'IPL'),
    ('El Dorado', 'Arkansas (AR)', 'ELD'),
    ('El Paso', 'Texas (TX)', 'ELP'),
    ('Elfin Cove', 'Alaska (AK)', 'ELV'),
    ('Elim', 'Alaska (AK)', 'ELI'),
    ('Elko', 'Nevada (NV)', 'EKO'),
    ('Elmira', 'New York (NY)', 'ELM'),
    ('Ely', 'Minnesota (MN)', 'LYU'),
    ('Emmonak', 'Alaska (AK)', 'EMK'),
    ('Endicott', 'New York (NY)', 'BGM'),
    ('Enid', 'Oklahoma (OK)', 'WDG'),
    ('Erie', 'Pennsylvania (PA)', 'ERI'),
    ('Escanaba', 'Michigan (MI)', 'ESC'),
    ('Eugene', 'Oregon (OR)', 'EUG'),
    ('Eureka/Arcata', 'California (CA)', 'ACV'),
    ('Eureka', 'Nevada (NV)', 'EUE'),
    ('Evansville', 'Indiana (IN)', 'EVV'),
    ('Fairbanks', 'Alaska (AK)', 'FAI'),
    ('Fargo', 'North Dakota (ND)', 'FAR'),
    ('Fayetteville', 'Arkansas (AR) - Municipal/Drake', 'FYV'),
    ('Fayetteville', 'Arkansas (AR) - Northwest Arkansas Regional', 'XNA'),
    ('Fayetteville', 'North Carolina (NC)', 'FAY'),
    ('Flagstaff', 'Arizona (AZ)', 'FLG'),
    ('Flint', 'Michigan (MI)', 'FNT'),
    ('Florence', 'South Carolina (SC)', 'FLO'),
    ('Florence/Muscle Shoals/Sheffield', 'Alabama (AL)', 'MSL'),
    ('Fort Collins/Loveland', 'Colorado (CO) - Municipal Airport', 'FNL'),
    ('Fort Dodge', 'Iowa (IA)', 'FOD'),
    ('Fort Lauderdale', 'Florida (FL)', 'FLL'),
    ('Fort Leonard Wood', 'Missouri (MO)', 'TBN'),
    ('Fort Myers', 'Florida (FL)', 'RSW'),
    ('Fort Smith', 'Arkansas (AR)', 'FSM'),
    ('Fort Walton Beach', 'Florida (FL)', 'VPS'),
    ('Fort Wayne', 'Indiana (IN)', 'FWA'),
    ('Fort Worth/Dallas', 'Texas (TX)', 'DFW'),
    ('Franklin', 'Pennsylvania (PA)', 'FKL'),
    ('Fresno', 'California (CA)', 'FAT'),
    ('Gainesville', 'Florida (FL)', 'GNV'),
    ('Gallup', 'New Mexico (NM)', 'GUP'),
    ('Garden City', 'Kansas (KS)', 'GCK'),
    ('Gary', 'Indiana (IN)', 'GYY'),
    ('Gillette', 'Wyoming (WY)', 'GCC'),
    ('Gladewater/Kilgore', 'Texas (TX)', 'GGG'),
    ('Glasgow', 'Montana (MT)', 'GGW'),
    ('Glendive', 'Montana (MT)', 'GDV'),
    ('Golovin', 'Alaska (AK)', 'GLV'),
    ('Goodnews Bay', 'Alaska (AK)', 'GNU'),
    ('Grand Forks', 'North Dakota (ND)', 'GFK'),
    ('Grand Island', 'Nebraska (NE)', 'GRI'),
    ('Grand Junction', 'Colorado (CO)', 'GJT'),
    ('Grand Rapids', 'Michigan (MI)', 'GRR'),
    ('Grand Rapids', 'Minnesota (MN)', 'GPZ'),
    ('Grayling', 'Alaska (AK)', 'KGX'),
    ('Great Falls', 'Montana (MT)', 'GTF'),
    ('Green Bay', 'Wisconsin (WI)', 'GRB'),
    ('Greensboro', 'North Carolina (NC)', 'GSO'),
    ('Greenville', 'Mississippi (MS)', 'GLH'),
    ('Greenville', 'North Carolina (NC)', 'PGV'),
    ('Greenville/Spartanburg', 'South Carolina (SC)', 'GSP'),
    ('Groton/New London', 'Connecticut (CT)', 'GON'),
    ('Gulfport', 'Mississippi (MS)', 'GPT'),
    ('Gunnison', 'Colorado (CO)', 'GUC'),
    ('Gustavus', 'Alaska (AK)', 'GST'),
    ('Hagerstown', 'Maryland (MD)', 'HGR'),
    ('Hailey', 'Idaho (ID)', 'SUN'),
    ('Haines', 'Alaska (AK)', 'HNS'),
    ('Hampton', 'Virginia (VA)', 'PHF'),
    ('Hana', 'Hawaii (HI) - Island of Maui', 'HNM'),
    ('Hanapepe', 'Hawaii (HI)', 'PAK'),
    ('Hancock', 'Michigan (MI)', 'CMX'),
    ('Hanover', 'New Hampshire (NH)', 'LEB'),
    ('Harlingen', 'Texas (TX)', 'HRL'),
    ('Harrisburg', 'Pennsylvania (PA)', 'MDT'),
    ('Harrison', 'Arkansas (AR)', 'HRO'),
    ('Hartford', 'Connecticut (CT)', 'BDL'),
    ('Havasupai', 'Arizona (AZ)', 'HAE'),
    ('Havre', 'Montana (MT)', 'HVR'),
    ('Hayden', 'Colorado (CO)', 'HDN'),
    ('Hays', 'Kansas (KS)', 'HYS'),
    ('Healy Lake', 'Alaska (AK)', 'HKB'),
    ('Helena', 'Montana (MT)', 'HLN'),
    ('Hendersonville', 'North Carolina (NC)', 'AVL'),
    ('Hibbing/Chisholm', 'Minnesota (MN)', 'HIB'),
    ('Hickory', 'North Carolina (NC)', 'HKY'),
    ('High Point', 'North Carolina (NC)', 'GSO'),
    ('Hilo', 'Hawaii (HI) - Island of Hawaii', 'ITO'),
    ('Hilton Head', 'South Carolina (SC)', 'HHH'),
    ('Hobbs', 'New Mexico (NM)', 'HBB'),
    ('Hollis', 'Alaska (AK)', 'HYL'),
    ('Holy Cross', 'Alaska (AK)', 'HCR'),
    ('Homer', 'Alaska (AK)', 'HOM'),
    ('Honolulu', 'Hawaii (HI) - Island of Oahu', 'HNL'),
    ('Hoolehua', 'Hawaii (HI) - Island of Molokai', 'MKK'),
    ('Hoonah', 'Alaska (AK)', 'HNH'),
    ('Hooper Bay', 'Alaska (AK)', 'HPB'),
    ('Hot Springs', 'Arkansas (AR)', 'HOT'),
    ('Houston', 'Texas (TX) - All airports', 'HOU'),
    ('Houston', 'Texas (TX) - Hobby', 'HOU'),
    ('Houston', 'Texas (TX) - Intercontinental', 'IAH'),
    ('Hughes', 'Alaska (AK)', 'HUS'),
    ('Huntington', 'West Virginia (WV)/Ashland, KY', 'HTS'),
    ('Huntsville', 'Alabama (AL)', 'HSV'),
    ('Huron', 'South Dakota (SD)', 'HON'),
    ('Huslia', 'Alaska (AK)', 'HSL'),
    ('Hyannis', 'Massachusetts (MA)', 'HYA'),
    ('Hydaburg', 'Alaska (AK)', 'HYG'),
    ('Idaho Falls', 'Idaho (ID)', 'IDA'),
    ('Igiugig', 'Alaska (AK)', 'IGG'),
    ('Iliamna', 'Alaska (AK)', 'ILI'),
    ('Imperial', 'California (CA)', 'IPL'),
    ('Indianapolis', 'Indiana (IN)', 'IND'),
    ('International Falls', 'Minnesota (MN)', 'INL'),
    ('Inyokern', 'California (CA)', 'IYK'),
    ('Iron Mountain', 'Michigan (MI)', 'IMT'),
    ('Ironwood', 'Michigan (MI)', 'IWD'),
    ('Islip', 'New York (NY)', 'ISP'),
    ('Ithaca', 'New York (NY)', 'ITH'),
    ('Jackson Hole', 'Wyoming (WY)', 'JAC'),
    ('Jackson', 'Mississippi (MS)', 'JAN'),
    ('Jackson', 'Tennessee (TN)', 'MKL'),
    ('Jacksonville', 'Florida (FL)', 'JAX'),
    ('Jacksonville', 'North Carolina (NC)', 'OAJ'),
    ('Jamestown', 'North Dakota (ND)', 'JMS'),
    ('Jamestown', 'New York (NY)', 'JHW'),
    ('Janesville', 'Wisconsin (WI)', 'JVL'),
    ('Johnson City', 'New York (NY)', 'BGM'),
    ('Johnson City', 'Tennessee (TN)', 'TRI'),
    ('Johnstown', 'Pennsylvania (PA)', 'JST'),
    ('Jonesboro', 'Arkansas (AR)', 'JBR'),
    ('Joplin', 'Missouri (MO)', 'JLN'),
    ('Juneau', 'Alaska (AK)', 'JNU'),
    ('Kahului', 'Hawaii (HI) - Island of Maui,', 'OGG'),
    ('Kake', 'Alaska (AK)', 'KAE'),
    ('Kakhonak', 'Alaska (AK)', 'KNK'),
    ('Kalamazoo', 'Michigan (MI)', 'AZO'),
    ('Kalaupapa', 'Hawaii (HI) - Island of Molokai,', 'LUP'),
    ('Kalskag', 'Alaska (AK)', 'KLG'),
    ('Kaltag', 'Alaska (AK)', 'KAL'),
    ('Kamuela', 'Hawaii (HI) - Island of Hawaii,', 'MUE'),
    ('Kansas City', 'Missouri (MO)', 'MCI'),
    ('Kapalua', 'Hawaii (HI) - Island of Maui,', 'JHM'),
    ('Kasaan', 'Alaska (AK)', 'KXA'),
    ('Kasigluk', 'Alaska (AK)', 'KUK'),
    ('Kauai Island/Lihue', 'Hawaii (HI)', 'LIH'),
    ('Kearney', 'Nebraska (NE)', 'EAR'),
    ('Keene', 'New Hampshire (NH)', 'EEN'),
    ('Kenai', 'Alaska (AK)', 'ENA'),
    ('Ketchikan', 'Alaska (AK)', 'KTN'),
    ('Key West', 'Florida (FL)', 'EYW'),
    ('Keystone', 'Colorado (CO) - Van service', 'QKS'),
    ('Kiana', 'Alaska (AK)', 'IAN'),
    ('Kilgore/Gladewater', 'Texas (TX)', 'GGG'),
    ('Killeen', 'Texas (TX)', 'ILE'),
    ('King Cove', 'Alaska (AK)', 'KVC'),
    ('King Salmon', 'Alaska (AK)', 'AKN'),
    ('Kingman', 'Arizona (AZ)', 'IGM'),
    ('Kingsport', 'Tennessee (TN)', 'TRI'),
    ('Kipnuk', 'Alaska (AK)', 'KPN'),
    ('Kirksville', 'Missouri (MO)', 'IRK'),
    ('Kivalina', 'Alaska (AK)', 'KVL'),
    ('Klamath Falls', 'Oregon (OR)', 'LMT'),
    ('Klawock', 'Alaska (AK)', 'KLW'),
    ('Knoxville', 'Tennessee (TN)', 'TYS'),
    ('Kobuk', 'Alaska (AK)', 'OBU'),
    ('Kodiak', 'Alaska (AK)', 'ADQ'),
    ('Kona', 'Hawaii (HI) - Island of Hawaii', 'KOA'),
    ('Kongiganak', 'Alaska (AK)', 'KKH'),
    ('Kotlik', 'Alaska (AK)', 'KOT'),
    ('Kotzebue', 'Alaska (AK)', 'OTZ'),
    ('Koyukuk', 'Alaska (AK)', 'KYU'),
    ('Kwethluk', 'Alaska (AK)', 'KWT'),
    ('Kwigillingok', 'Alaska (AK)', 'KWK'),
    ('La Crosse', 'Wisconsin (WI)', 'LSE'),
    ('Lafayette', 'Indiana (IN)', 'LAF'),
    ('Lafayette', 'Louisiana (LA)', 'LFT'),
    ('Lake Charles', 'Louisiana (LA)', 'LCH'),
    ('Lake Havasu City', 'Arizona (AZ)', 'HII'),
    ('Lake Minchumina', 'Alaska (AK)', 'LMA'),
    ('Lanai City', 'Hawaii (HI) - Island of Lanai', 'LNY'),
    ('Lancaster', 'Pennsylvania (PA)', 'LNS'),
    ('Lansing', 'Michigan (MI)', 'LAN'),
    ('Laramie', 'Wyoming (WY)', 'LAR'),
    ('Laredo', 'Texas (TX)', 'LRD'),
    ('Las Vegas', 'Nevada (NV)', 'LAS'),
    ('Latrobe', 'Pennsylvania (PA)', 'LBE'),
    ('Laurel', 'Mississippi (MS)', 'PIB'),
    ('Lawton', 'Oklahoma (OK)', 'LAW'),
    ('Lebanon', 'New Hampshire (NH)', 'LEB'),
    ('Levelock', 'Alaska (AK)', 'KLL'),
    ('Lewisburg', 'West Virginia (WV)', 'LWB'),
    ('Lewiston', 'Idaho (ID)', 'LWS'),
    ('Lewistown', 'Montana (MT)', 'LWT'),
    ('Lexington', 'Kentucky (KY)', 'LEX'),
    ('Liberal', 'Kansas (KS)', 'LBL'),
    ('Lihue', 'Hawaii (HI) - Island of Kaui', 'LIH'),
    ('Lincoln', 'Nebraska (NE)', 'LNK'),
    ('Little Rock', 'Arkansas (AR)', 'LIT'),
    ('Long Beach', 'California (CA)', 'LGB'),
    ('Longview', 'Texas (TX)', 'GGG'),
    ('Lopez Island', 'Washington (WA)', 'LPS'),
    ('Los Angeles', 'California (CA)', 'LAX'),
    ('Louisville', 'Kentucky (KY)', 'SDF'),
    ('Loveland/Fort Collins', 'Colorado (CO) - Municipal Airport', 'FNL'),
    ('Lubbock', 'Texas (TX)', 'LBB'),
    ('Macon', 'Georgia (GA)', 'MCN'),
    ('Madison', 'Wisconsin (WI)', 'MSN'),
    ('Madras', 'Oregon (OR)', 'MDJ'),
    ('Manchester', 'New Hampshire (NH)', 'MHT'),
    ('Manhattan', 'Kansas (KS)', 'MHK'),
    ('Manistee', 'Michigan (MI)', 'MBL'),
    ('Mankato', 'Minnesota (MN)', 'MKT'),
    ('Manley Hot Springs', 'Alaska (AK)', 'MLY'),
    ('Manokotak', 'Alaska (AK)', 'KMO'),
    ('Marietta', 'Ohio (OH)/Parkersburg, WV', 'PKB'),
    ('Marion', 'Illinois (IL)', 'MWA'),
    ('Marquette', 'Michigan (MI)', 'MQT'),
    ('Marshall', 'Alaska (AK)', 'MLL'),
    ("Martha's Vineyard", 'Massachusetts (MA)', 'MVY'),
    ('Martinsburg', 'Pennsylvania (PA)', 'AOO'),
    ('Mason City', 'Iowa (IA)', 'MCW'),
    ('Massena', 'New York (NY)', 'MSS'),
    ('Maui', 'Hawaii (HI)', 'OGG'),
    ('Mcallen', 'Texas (TX)', 'MFE'),
    ('Mccook', 'Nebraska (NE)', 'MCK'),
    ('Mcgrath', 'Alaska (AK)', 'MCG'),
    ('Medford', 'Oregon (OR)', 'MFR'),
    ('Mekoryuk', 'Alaska (AK)', 'MYU'),
    ('Melbourne', 'Florida (FL)', 'MLB'),
    ('Memphis', 'Tennessee (TN)', 'MEM'),
    ('Merced', 'California (CA)', 'MCE'),
    ('Meridian', 'Mississippi (MS)', 'MEI'),
    ('Metlakatla', 'Alaska (AK)', 'MTM'),
    ('Meyers Chuck', 'Alaska (AK)', 'WMK'),
    ('Miami', 'Florida (FL) - International', 'MIA'),
    ('Miami', 'Florida (FL) - Sea Plane Base', 'MPB'),
    ('Midland', 'Michigan (MI)', 'MBS'),
    ('Midland/Odessa', 'Texas (TX)', 'MAF'),
    ('Miles City', 'Montana (MT)', 'MLS'),
    ('Milwaukee', 'Wisconsin (WI)', 'MKE'),
    ('Minneapolis', 'Minnesota (MN)', 'MSP'),
    ('Minot', 'North Dakota (ND)', 'MOT'),
    ('Minto', 'Alaska (AK)', 'MNT'),
    ('Mission', 'Texas (TX)', 'MFE'),
    ('Missoula', 'Montana (MT)', 'MSO'),
    ('Moab', 'Utah (UT)', 'CNY'),
    ('Mobile', 'Alabama (AL)', 'MOB'),
    ('Modesto', 'California (CA)', 'MOD'),
    ('Moline', 'Illinois (IL)', 'MLI'),
    ('Monroe', 'Louisiana (LA)', 'MLU'),
    ('Monterey', 'California (CA)', 'MRY'),
    ('Montgomery', 'Alabama (AL)', 'MGM'),
    ('Montrose', 'Colorado (CO)', 'MTJ'),
    ('Morgantown', 'West Virginia (WV)', 'MGW'),
    ('Moses Lake', 'Washington (WA)', 'MWH'),
    ('Mountain Home', 'Arkansas (AR)', 'WMH'),
    ('Mountain Village', 'Alaska (AK)', 'MOU'),
    ('Muscle Shoals', 'Alabama (AL)', 'MSL'),
    ('Muskegon', 'Michigan (MI)', 'MKG'),
    ('Myrtle Beach', 'South Carolina (SC)', 'MYR'),
    ('Nantucket', 'Massachusetts (MA)', 'ACK'),
    ('Napakiak', 'Alaska (AK)', 'WNA'),
    ('Napaskiak', 'Alaska (AK)', 'PKA'),
    ('Naples', 'Florida (FL)', 'APF'),
    ('Nashville', 'Tennessee (TN)', 'BNA'),
    ('Naukiti', 'Alaska (AK)', 'NKI'),
    ('Nelson Lagoon', 'Alaska (AK)', 'NLG'),
    ('New Chenega', 'Alaska (AK)', 'NCN'),
    ('New Haven', 'Connecticut (CT)', 'HVN'),
    ('New Koliganek', 'Alaska (AK)', 'KGK'),
    ('New Orleans', 'Louisiana (LA)', 'MSY'),
    ('New Stuyahok', 'Alaska (AK)', 'KNW'),
    ('New York', 'New York (NY) - All airports', 'NYC'),
    ('New York', 'New York (NY) - Kennedy', 'JFK'),
    ('New York', 'New York (NY) - La Guardia', 'LGA'),
    ('Newark', 'New Jersey (NJ)', 'EWR'),
    ('Newburgh/Stewart Field', 'New York (NY)', 'SWF'),
    ('Newport News', 'Virginia (VA)', 'PHF'),
    ('Newtok', 'Alaska (AK)', 'WWT'),
    ('Nightmute', 'Alaska (AK)', 'NME'),
    ('Nikolai', 'Alaska (AK)', 'NIB'),
    ('Nikolski', 'Alaska (AK)', 'IKO'),
    ('Noatak', 'Alaska (AK)', 'WTK'),
    ('Nome', 'Alaska (AK)', 'OME'),
    ('Nondalton', 'Alaska (AK)', 'NNL'),
    ('Noorvik', 'Alaska (AK)', 'ORV'),
    ('Norfolk', 'Nebraska (NE)', 'OFK'),
    ('Norfolk', 'Virginia (VA)', 'ORF'),
    ('North Bend', 'Oregon (OR)', 'OTH'),
    ('North Platte', 'Nebraska (NE)', 'LBF'),
    ('Northway', 'Alaska (AK)', 'ORT'),
    ('Nuiqsut', 'Alaska (AK)', 'NUI'),
    ('Nulato', 'Alaska (AK)', 'NUL'),
    ('Nunapitchuk', 'Alaska (AK)', 'NUP'),
    ('Oakland', 'California (CA)', 'OAK'),
    ('Odessa/Midland', 'Texas (TX)', 'MAF'),
    ('Ogdensburg', 'New York (NY)', 'OGS'),
    ('Oklahoma City', 'Oklahoma (OK)', 'OKC'),
    ('Omaha', 'Nebraska (NE)', 'OMA'),
    ('Ontario', 'California (CA)', 'ONT'),
    ('Orange County', 'California (CA)', 'SNA'),
    ('Orlando', 'Florida (FL) - Herndon', 'ORL'),
    ('Orlando', 'Florida (FL) - International', 'MCO'),
    ('Oshkosh', 'Wisconsin (WI)', 'OSH'),
    ('Ottumwa', 'Iowa (IA)', 'OTM'),
    ('Owensboro', 'Kentucky (KY)', 'OWB'),
    ('Oxnard/Ventura', 'California (CA)', 'OXR'),
    ('Paducah', 'Kentucky (KY)', 'PAH'),
    ('Page', 'Arizona (AZ)', 'PGA'),
    ('Palm Springs', 'California (CA)', 'PSP'),
    ('Panama City', 'Florida (FL)', 'PFN'),
    ('Parkersburg', 'West Virginia (WV)/Marietta, OH', 'PKB'),
    ('Pasco', 'Washington (WA)', 'PSC'),
    ('Pedro Bay', 'Alaska (AK)', 'PDB'),
    ('Pelican', 'Alaska (AK)', 'PEC'),
    ('Pellston', 'Michigan (MI)', 'PLN'),
    ('Pendleton', 'Oregon (OR)', 'PDT'),
    ('Pensacola', 'Florida (FL)', 'PNS'),
    ('Peoria', 'Illinois (IL)', 'PIA'),
    ('Perryville', 'Alaska (AK)', 'KPV'),
    ('Petersburg', 'Alaska (AK)', 'PSG'),
    ('Philadelphia', 'Pennsylvania (PA) - International', 'PHL'),
    ('Philadelphia', 'Pennsylvania (PA) - Trenton/Mercer NJ', 'TTN'),
    ('Phoenix', 'Arizona (AZ)', 'PHX'),
    ('Pierre', 'South Dakota (SD)', 'PIR'),
    ('Pilot Point', 'Alaska (AK) - Ugashnik Bay', 'UGB'),
    ('Pilot Point', 'Alaska (AK)', 'PIP'),
    ('Pilot Station', 'Alaska (AK)', 'PQS'),
    ('Pittsburgh', 'Pennsylvania (PA)', 'PIT'),
    ('Platinum', 'Alaska (AK)', 'PTU'),
    ('Plattsburgh', 'New York (NY)', 'PLB'),
    ('Pocatello', 'Idaho (ID)', 'PIH'),
    ('Point Baker', 'Alaska (AK)', 'KPB'),
    ('Point Hope', 'Alaska (AK)', 'PHO'),
    ('Point Lay', 'Alaska (AK)', 'PIZ'),
    ('Ponca City', 'Oklahoma (OK)', 'PNC'),
    ('Ponce', 'Puerto Rico', 'PSE'),
    ('Port Alsworth', 'Alaska (AK)', 'PTA'),
    ('Port Angeles', 'Washington (WA)', 'CLM'),
    ('Port Arthur/Beaumont', 'Texas (TX)', 'BPT'),
    ('Port Clarence', 'Alaska (AK)', 'KPC'),
    ('Port Heiden', 'Alaska (AK)', 'PTH'),
    ('Port Moller', 'Alaska (AK)', 'PML'),
    ('Port Protection', 'Alaska (AK)', 'PPV'),
    ('Portage Creek', 'Alaska (AK)', 'PCA'),
    ('Portland', 'Maine (ME)', 'PWM'),
    ('Portland', 'Oregon (OR)', 'PDX'),
    ('Portsmouth', 'New Hampshire (NH)', 'PSM'),
    ('Poughkeepsie', 'New York (NY)', 'POU'),
    ('Prescott', 'Arizona (AZ)', 'PRC'),
    ('Presque Isle', 'Maine (ME)', 'PQI'),
    ('Princeton', 'West Virginia (WV)', 'BLF'),
    ('Providence', 'Rhode Island (RI)', 'PVD'),
    ('Provincetown', 'Massachusetts (MA)', 'PVC'),
    ('Prudhoe Bay/Deadhorse', 'Alaska (AK)', 'SCC'),
    ('Pueblo', 'Colorado (CO)', 'PUB'),
    ('Pullman', 'Washington (WA)', 'PUW'),
    ('Quincy', 'Illinois (IL)', 'UIN'),
    ('Quinhagak', 'Alaska (AK)', 'KWN'),
    ('Raleigh/Durham', 'North Carolina (NC)', 'RDU'),
    ('Rampart', 'Alaska (AK)', 'RMP'),
    ('Rapid City', 'South Dakota (SD)', 'RAP'),
    ('Reading', 'Pennsylvania (PA)', 'RDG'),
    ('Red Devil', 'Alaska (AK)', 'RDV'),
    ('Redding', 'California (CA)', 'RDD'),
    ('Redmond', 'Oregon (OR)', 'RDM'),
    ('Reno', 'Nevada (NV)', 'RNO'),
    ('Rhinelander', 'Wisconsin (WI),', 'RHI'),
    ('Richmond', 'Virginia (VA)', 'RIC'),
    ('Riverton', 'Wyoming (WY)', 'RIW'),
    ('Roanoke', 'Virginia (VA)', 'ROA'),
    ('Roche Harbor', 'Washington (WA)', 'RCE'),
    ('Rochester', 'Minnesota (MN)', 'RST'),
    ('Rochester', 'New York (NY)', 'ROC'),
    ('Rock Springs', 'Wyoming (WY)', 'RKS'),
    ('Rockford', 'Illinois (IL) - Park&Ride Bus', 'ZRF'),
    ('Rockford', 'Illinois (IL) - Van Galder Bus', 'ZRK'),
    ('Rockland', 'Maine (ME)', 'RKD'),
    ('Rosario', 'Washington (WA)', 'RSJ'),
    ('Roswell', 'New Mexico (NM)', 'ROW'),
    ('Ruby', 'Alaska (AK)', 'RBY'),
    ('Russian Mission', 'Alaska (AK)', 'RSH'),
    ('Rutland', 'Vermont (VT)', 'RUT'),
    ('Sacramento', 'California (CA)', 'SMF'),
    ('Saginaw', 'Michigan (MI)', 'MBS'),
    ('Saint Cloud', 'Minnesota (MN)', 'STC'),
    ('Saint George Island', 'Alaska (AK)', 'STG'),
    ('Saint George', 'Utah (UT)', 'SGU'),
    ('Saint Louis', 'Missouri (MO)', 'STL'),
    ("Saint Mary's", 'Alaska (AK)', 'KSM'),
    ('Saint Michael', 'Alaska (AK)', 'SMK'),
    ('Saint Paul Island', 'Alaska (AK)', 'SNP'),
    ('Salem', 'Oregon (OR)', 'SLE'),
    ('Salina', 'Kansas (KS)', 'SLN'),
    ('Salisbury-Ocean City', 'Maryland (MD)', 'SBY'),
    ('Salt Lake City', 'Utah (UT)', 'SLC'),
    ('San Angelo', 'Texas (TX)', 'SJT'),
    ('San Antonio', 'Texas (TX)', 'SAT'),
    ('San Diego', 'California (CA)', 'SAN'),
    ('San Francisco', 'California (CA)', 'SFO'),
    ('San Jose', 'California (CA)', 'SJC'),
    ('San Juan', 'Puerto Rico', 'SJU'),
    ('San Luis Obispo', 'California (CA)', 'SBP'),
    ('Sand Point', 'Alaska (AK)', 'SDP'),
    ('Santa Ana', 'California (CA)', 'SNA'),
    ('Santa Barbara', 'California (CA)', 'SBA'),
    ('Santa Fe', 'New Mexico (NM)', 'SAF'),
    ('Santa Maria', 'California (CA)', 'SMX'),
    ('Santa Rosa', 'California (CA)', 'STS'),
    ('Saranac Lake', 'New York (NY)', 'SLK'),
    ('Sarasota', 'Florida (FL)', 'SRQ'),
    ('Sault Ste Marie', 'Michigan (MI),', 'CIU'),
    ('Savannah', 'Georgia (GA)', 'SAV'),
    ('Savoonga', 'Alaska (AK)', 'SVA'),
    ('Scammon Bay', 'Alaska (AK)', 'SCM'),
    ('Scottsbluff', 'Nebraska (NE)', 'BFF'),
    ('Scottsdale', 'Arizona (AZ)', 'SDL'),
    ('Scranton', 'Pennsylvania (PA)', 'AVP'),
    ('Seattle', 'Washington (WA) - Lake Union SPB', 'LKE'),
    ('Seattle', 'Washington (WA) - Seattle/Tacoma International', 'SEA'),
    ('Selawik', 'Alaska (AK)', 'WLK'),
    ('Seward', 'Alaska (AK)', 'SWD'),
    ('Shageluk', 'Alaska (AK)', 'SHX'),
    ('Shaktoolik', 'Alaska (AK)', 'SKK'),
    ('Sheffield/Florence/Muscle Shoals', 'Alabama (AL)', 'MSL'),
    ('Sheldon Point', 'Alaska (AK)', 'SXP'),
    ('Sheridan', 'Wyoming (WY)', 'SHR'),
    ('Shishmaref', 'Alaska (AK)', 'SHH'),
    ('Shreveport', 'Louisiana (LA)', 'SHV'),
    ('Shungnak', 'Alaska (AK)', 'SHG'),
    ('Silver City', 'New Mexico (NM)', 'SVC'),
    ('Sioux City', 'Iowa (IA)', 'SUX'),
    ('Sioux Falls', 'South Dakota (SD)', 'FSD'),
    ('Sitka', 'Alaska (AK)', 'SIT'),
    ('Skagway', 'Alaska (AK)', 'SGY'),
    ('Sleetmore', 'Alaska (AK)', 'SLQ'),
    ('South Bend', 'Indiana (IN)', 'SBN'),
    ('South Naknek', 'Alaska (AK)', 'WSN'),
    ('Southern Pines', 'North Carolina (NC)', 'SOP'),
    ('Spartanburg/Greenville', 'South Carolina (SC)', 'GSP'),
    ('Spokane', 'Washington (WA)', 'GEG'),
    ('Springfield', 'Illinois (IL)', 'SPI'),
    ('Springfield', 'Missouri (MO)', 'SGF'),
    ('St Petersburg/Clearwater', 'Florida (FL)', 'PIE'),
    ('State College/University Park', 'Pennsylvania (PA)', 'SCE'),
    ('Staunton', 'Virginia (VA)', 'SHD'),
    ('Steamboat Springs', 'Colorado (CO)', 'SBS'),
    ('Stebbins', 'Alaska (AK)', 'WBB'),
    ('Stevens Point/Wausau', 'Wisconsin (WI)', 'CWA'),
    ('Stevens Village', 'Alaska (AK)', 'SVS'),
    ('Stewart Field/Newburgh', 'New York (NY)', 'SWF'),
    ('Stockton', 'California (CA)', 'SCK'),
    ('Stony River', 'Alaska (AK)', 'SRV'),
    ('Sun Valley', 'Idaho (ID)', 'SUN'),
    ('Syracuse', 'New York (NY)', 'SYR'),
    ('Takotna', 'Alaska (AK)', 'TCT'),
    ('Talkeetna', 'Alaska (AK)', 'TKA'),
    ('Tallahassee', 'Florida (FL)', 'TLH'),
    ('Tampa', 'Florida (FL)', 'TPA'),
    ('Tanana', 'Alaska (AK)', 'TAL'),
    ('Taos', 'New Mexico (NM)', 'TSM'),
    ('Tatitlek', 'Alaska (AK)', 'TEK'),
    ('Teller Mission', 'Alaska (AK)', 'KTS'),
    ('Telluride', 'Colorado (CO)', 'TEX'),
    ('Tenakee Springs', 'Alaska (AK)', 'TKE'),
    ('Terre Haute', 'Indiana (IN)', 'HUF'),
    ('Tetlin', 'Alaska (AK)', 'TEH'),
    ('Texarkana', 'Arkansas (AR)', 'TXK'),
    ('Thief River Falls', 'Minnesota (MN)', 'TVF'),
    ('Thorne Bay', 'Alaska (AK)', 'KTB'),
    ('Tin City', 'Alaska (AK)', 'TNC'),
    ('Togiak Village', 'Alaska (AK)', 'TOG'),
    ('Tok', 'Alaska (AK)', 'TKJ'),
    ('Toksook Bay', 'Alaska (AK)', 'OOK'),
    ('Toledo', 'Ohio (OH)', 'TOL'),
    ('Topeka', 'Kansas (KS)', 'FOE'),
    ('Traverse City', 'Michigan (MI)', 'TVC'),
    ('Trenton/Mercer', 'New Jersey (NJ)', 'TTN'),
    ('Tucson', 'Arizona (AZ)', 'TUS'),
    ('Tulsa', 'Oklahoma (OK)', 'TUL'),
    ('Tuluksak', 'Alaska (AK)', 'TLT'),
    ('Tuntutuliak', 'Alaska (AK)', 'WTL'),
    ('Tununak', 'Alaska (AK)', 'TNK'),
    ('Tupelo', 'Mississippi (MS)', 'TUP'),
    ('Tuscaloosa', 'Alabama (AL)', 'TCL'),
    ('Twin Falls', 'Idaho (ID)', 'TWF'),
    ('Twin Hills', 'Alaska (AK)', 'TWA'),
    ('Tyler', 'Texas (TX)', 'TYR'),
    ('Unalakleet', 'Alaska (AK)', 'UNK'),
    ('Urbana/Champaign', 'Illinois (IL)', 'CMI'),
    ('Utica', 'New York (NY)', 'UCA'),
    ('Utopia Creek', 'Alaska (AK)', 'UTO'),
    ('Vail', 'Colorado (CO) - Eagle County Airport', 'EGE'),
    ('Vail', 'Colorado (CO) - Van service', 'QBF'),
    ('Valdez', 'Alaska (AK)', 'VDZ'),
    ('Valdosta', 'Georgia (GA)', 'VLD'),
    ('Valparaiso', 'Florida (FL)', 'VPS'),
    ('Venetie', 'Alaska (AK)', 'VEE'),
    ('Ventura/Oxnard', 'California (CA)', 'OXR'),
    ('Vernal', 'Utah (UT)', 'VEL'),
    ('Victoria', 'Texas (TX)', 'VCT'),
    ('Visalia', 'California (CA)', 'VIS'),
    ('Waco', 'Texas (TX)', 'ACT'),
    ('Wainwright', 'Alaska (AK)', 'AIN'),
    ('Wales', 'Alaska (AK)', 'WAA'),
    ('Walla Walla', 'Washington (WA)', 'ALW'),
    ('Washington DC', 'District of Columbia (DC) - All airports', '(WAS)'),
    ('Washington DC', 'District of Columbia (DC) - Dulles', '(IAD)'),
    ('Washington DC', 'District of Columbia (DC) - National', '(DCA)'),
    ('Waterfall', 'Alaska (AK)', 'KWF'),
    ('Waterloo', 'Iowa (IA)', 'ALO'),
    ('Watertown', 'New York (NY)', 'ART'),
    ('Watertown', 'South Dakota (SD)', 'ATY'),
    ('Wausau/Stevens Point', 'Wisconsin (WI)', 'CWA'),
    ('Wenatchee', 'Washington (WA)', 'EAT'),
    ('West Palm Beach', 'Florida (FL)', 'PBI'),
    ('West Yellowstone', 'Montana (MT)', 'WYS'),
    ('Westchester County', 'New York (NY)', 'HPN'),
    ('Westerly', 'Rhode Island (RI)', 'WST'),
    ('Westsound', 'Washington (WA)', 'WSX'),
    ('Whale Pass', 'Alaska (AK)', 'WWP'),
    ('White Mountain', 'Alaska (AK)', 'WMO'),
    ('White River', 'Vermont (VT)', 'LEB'),
    ('Wichita Falls', 'Texas (TX)', 'SPS'),
    ('Wichita', 'Kansas (KS)', 'ICT'),
    ('Wilkes Barre', 'Pennsylvania (PA)', 'AVP'),
    ('Williamsburg', 'Virginia (VA)', 'PHF'),
    ('Williamsport', 'Pennsylvania (PA)', 'IPT'),
    ('Williston', 'North Dakota (ND)', 'ISN'),
    ('Wilmington', 'North Carolina (NC)', 'ILM'),
    ('Windsor Locks', 'Connecticut (CT)', 'BDL'),
    ('Worcester', 'Massachusetts (MA)', 'ORH'),
    ('Worland', 'Wyoming (WY)', 'WRL'),
    ('Wrangell', 'Alaska (AK)', 'WRG'),
    ('Yakima', 'Washington (WA)', 'YKM'),
    ('Yakutat', 'Alaska (AK)', 'YAK'),
    ('Yellowstone/Cody', 'Wyoming (WY)', 'COD'),
    ('Youngstown', 'Ohio (OH)', 'YNG'),
    ('Yuma', 'Arizona (AZ)', 'YUM')
]
