# Generated by Django 3.0.5 on 2020-05-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.IntegerField(default=1)),
                ('cost_of_living', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('start_airport', models.CharField(max_length=200)),
                ('dest_airport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='trips.Location')),
                ('flight_carrier', models.CharField(max_length=200)),
                ('departure_time', models.DateTimeField(verbose_name='Departure date')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival date')),
                ('num_passengers', models.IntegerField(default=1)),
                ('num_bags', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Region'),
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=200)),
                ('locations', models.ManyToManyField(to='trips.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(default=0)),
                ('total_cost', models.IntegerField(default=0)),
                ('flight_list', models.ManyToManyField(to='trips.Flights')),
            ],
        ),
    ]
