# Generated by Django 3.0.5 on 2020-05-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_carrier', models.CharField(max_length=200)),
                ('departure_time', models.DateTimeField(verbose_name='Departure date')),
                ('arrival_time', models.DateTimeField(verbose_name='Arrival date')),
                ('num_passengers', models.IntegerField(default=1)),
                ('num_bags', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('flights', models.ManyToManyField(to='trips.Flight')),
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='dest_airport',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='flight_list',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='regions',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='region',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trips.Location'),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='trips.Location'),
        ),
        migrations.AddField(
            model_name='activity',
            name='locations',
            field=models.ManyToManyField(to='trips.Location'),
        ),
    ]
