# Generated by Django 3.0.5 on 2020-06-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='luxury',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='midrange',
            field=models.IntegerField(default=0),
        ),
    ]
