# Generated by Django 3.0.5 on 2020-06-01 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_flight_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='flights',
        ),
        migrations.AddField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='trips.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
